language: node_js
node_js:
- '6'
addons:
    firefox: latest
before_install:
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR
- sleep 3
install:
- npm config set spin false
- npm install
script:
- npm run travis

